#!/usr/bin/env bash

set -e
RUST_VERSION=$1;

USAGE=$(cat <<-END
Use the template to generate a configuration for a specific rust version.

Usage: $(basename $0) <rust-version>

Example:
    $(basename $0) 1.56

END
)

if [ -z $RUST_VERSION ]
then
	echo "$USAGE"
	exit 1
fi

# Using sed to modify a file in place has annoying different per platform
# syntax
function sed_in_place() {
    case "$(uname -s)" in
        Darwin)
            sed -i '' $@
            ;;

        *)
            sed -i $@
            ;;
    esac
}

TARGET=rust-$RUST_VERSION

if [ -d "$TARGET" ]; then
	echo "$TARGET already exists. Delete it first."
	exit 1
fi

echo "Generating $TARGET"

cp -r template $TARGET

for file in $TARGET/*
do
    sed_in_place "s/%RUST_VERSION%/$RUST_VERSION/" $file
done

cat << EOS > $TARGET/DO_NOT_EDIT
Changes to these file will be lost!
These files are generated by $(basename $0).
Instead of editing these files, edit the templates and rerun $(basename $0).
EOS

