name: Build, Test, and Publish Containers

on:
  push:
    branches:
      - mkirk/ghcr
      - main  # Trigger on pushes to main branch
  pull_request:
    branches:
      - main  # Also trigger on pull requests to main

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install deps
        run: sudo apt update && sudo apt install -y zsh

      - name: Clone test deps
        run: (cd .. && git clone https://github.com/georust/geo && git clone https://github.com/georust/proj)

      - name: Build
        run: ./run-rust.sh --all -- make build-all test-all

      - name: Login to GitHub Container Registry
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: ./run-rust.sh --all -- make publish-all
