name: Build, Test, and Publish Containers

on:
  push:
    branches:
      - mkirk-testing
      - main  # Trigger on pushes to main branch
  pull_request:
    branches:
      - main  # Also trigger on pull requests to main

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: make build test

      - name: Login to GitHub Container Registry
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: make publish
